### PR TITLE
Fixed minor typo in the pod.

### PR DESCRIPTION
**Pull request by manwar**
Hi @jhthorsen 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by jhthorsen** [comment]
Out of curiosity: Why does the commit message start with a hyphen?

**Comment by manwar** [comment]
I would say, my bad habit, I am trying to get rid off, sorry :-( 
Do you want me update the commit message?

**Comment by jhthorsen** [comment]
I'm not sure. Part of me wants to help you change habit, but another part just want to merge it.

You decide 🐰

**Comment by manwar** [comment]
Updated the commit message, I will try not to repeat the mistake.

**Comment by jhthorsen** [comment]
Awesome! Thank you.

Sorry for all the extra work. I wouldn't have asked you to unless you had suggested to change yourself 👍

**Comment by manwar** [comment]
Thank you for merging the PR.
It's good for me that you pointed out otherwise I would have carried on like these.

**Pull request merged**
