### PR TITLE
Fix POD to correctly explain how to amend base_url.

### PR DESCRIPTION
**Pull request by cliveholloway**

### CODE REVIEW

**Comment by mohawk2** [comment]
Thanks!

**Comment by jhthorsen** [comment]
@mohawk2: The PR is invalid. I will have to revert it.

**Comment by mohawk2** [comment]
@jhthorsen Are you going to steer @cliveholloway on what's wrong with it?

**Comment by jhthorsen** [comment]
@cliveholloway: Thanks for the PR! The issue was whitespace and some missing formatting in the POD. I've committed 200c2d5 now instead of asking you to create a new PR.

Hope that's ok.

**Comment by cliveholloway** [comment]
Oh, sure. I was looking at it, scratching my head for a second there, heh.
Guess I should have actually looked at the generated POD. Apologies.

**Pull request merged**
